version: "3"

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Map local code to container
      - .:/app/
      # Node modules folder built inside container
      - /app/node_modules
    tty: true
