# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build
          command: docker build -t danishmughal/react-docker-circle -f Dockerfile.dev .

      - run:
          name: Run tests
          command: docker run danishmughal/react-docker-circle yarn test --coverage

  deploy:
    docker:
      - image: "circleci/python:2.7"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build production assets
          command: docker build -t danishmughal/react-docker-circle .
      - run:
          name: Extract build assets
          command: |
            mkdir build
            chown -R $USER:$USER build
            docker create -it --name prod danishmughal/react-docker-circle bash
            docker cp prod:/build build
      - aws-s3/sync:
          from: build/
          to: "s3://react-docker-circle"
          overwrite: true

workflows:
  version: 2
  build-deploy:
    jobs:
      # - build
      - deploy:
          # requires:
          #   - build
          filters:
            branches:
              only:
                - master
                - staging
